### ISSUE TITLE
The error of code of LoadFacadeDatabase.mlx

### ISSUE THREAD

**Issue by momo-love** [zcemycl/Matlab-GAN#1]
I run the code（LoadFacadeDatabase.mlx）on the Matlab, and prompted for an error that he index exceeds the number of elements in the array .And LatCode.mat and ImgLib.mat were not found.

**Comment by zcemycl** [comment]
@momo-love Hi.
Please run LoadFacadeDatabase.m with the correct path in Line 3. At the end, please command to save those data (jpglist and pnglist) into matfile by, 
save('ImgLib.mat','jpglist')
save('LatCode.mat','pnglist')

I don't know how you get index error. 
1. I suspect you have not downloaded the extended version of facade dataset. If so, just comment out Lines 14-22 because it loads the extended stuff. 

Hope this can help :).

**Comment by zcemycl** [comment]
> I run the code（LoadFacadeDatabase.mlx）on the Matlab, and prompted for an error that he index exceeds the number of elements in the array .And LatCode.mat and ImgLib.mat were not found.

**Comment by zcemycl** [comment]
@momo-love 
Yup, I think this is what you got, 
"
Index exceeds the number of array elements (0).
Error in LoadFacadeDatabase (line 18)
    imj=imresize(imread([path filesjpg(i).name]),[256,256]);
"

I reproduced this error by changing my existing directory name 'CMP_facade_DB_extended' to 'CMP_facade_DB_extended1' so my system cannot detect the extended data. As the result, the index error should be caused by no such directory. So I recommend you either comment out the Lines 14-22 or download the extended version of facade dataset.
