### ISSUE TITLE
Testing code for cycleGAN

### ISSUE THREAD

**Issue by abhilasha2614** [zcemycl/Matlab-GAN#13]
I have trained cycleGAN for dehazing the fog but I don't know how to test and predict the images. I am trying to test the images which is given in the below link:
https://www.mathworks.com/help/deeplearning/ug/unsupervised-medical-image-denoising-using-cyclegan.html
 It would be great if you provide me the code for testing the GAN. 
If I am trying to predict I am getting the following error
Error using predict (line 85)
No valid system or dataset was specified.

Error in testing (line 59)
    generatedImageHD = predict(GradGBA,imageTestLD);

GradGBA is the weights obtained after training cycleGAN

kindly help me !!!!!!

**Comment by zcemycl** [comment]
@abhilasha2614 i don't know which script you are referring to. It is kinda weird you ask me about someone else script. 
Thats not in my repo. Thanks.

**Comment by abhilasha2614** [comment]
i referred your github code for cycleGAN and you have not mentioned how your testing the code so I need help in understanding how to test GAN. I used the code from matlab for testing part alone as I trained the images with your code but it was having some issue so that's why I have mentioned that link. For your kind information I did not refer other repository I needed help in understanding  your cycleGAN code as I am new to GAN. 

Thank you

**Comment by zcemycl** [comment]
@abhilasha2614 if you trained a gan based on my code, you would have got a plot showing the progress of losses and output images over epochs. That basically outlined how you reuse the weights, but not with oop, it is just a function.

Like 
```
Output = Generator(params, Inputs)
```

It has clearly stated already unless you have a lack of understandings about custom training loop and neural network, and how to read code logically and systematically. You are not new to gan, you are new to programming and neural network in general, please read and debug line by line instead of just running the code.
